# Generated by Django 3.2.23 on 2024-01-18 21:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 18, 21, 36, 41, 575332, tzinfo=utc)),
        ),
    ]
